### PR TITLE
Adding NodeIDs into the source code for apebrain-proofing

### PR DESCRIPTION
**Pull request by Weebifying**
shoutout to geode for making this awesome nodeids mod that i copied and pasted

### CODE REVIEW

**Comment by Weebifying** [comment]
can i finally have the dev badge now 👉👈

**Comment by Cvolton** [comment]
this is not getting accepted to the index btw

**Comment by Weebifying** [comment]
aw man

**Comment by coopeeo** [comment]
awwwwwwwwwwwwwwww
at least theres a new commit that adds more simplified errors to end users

**Pull request closed without merging**
